# -*- coding: utf-8 -*-
"""TP2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1294Huz2lKiy5FExT1vqjq5ntoUySQEA1

# Segundo trabajo práctico
## Ciencia de Datos TA047 - cátedra Martinelli
## Primer cuatrimestre 2026 - Melanie Belén García Lapegna 111848
## Link al notebook : https://colab.research.google.com/drive/1294Huz2lKiy5FExT1vqjq5ntoUySQEA1?usp=sharing

Esta segunda entrega tiene como objetivo aplicar las tecnicas de **Machine Learning** vistas en clase sobre un conjunto de datos.

El trabajo se estructura en varias etapas:
primero la **elección del dataset**, luego la **limpieza y el análisis exploratorio de datos**, para finalente poder **plantear y resolver un problema de predicción**.

El proceso comenzara con una etapa de **modelado simple**, la cual se utilizara como _baseline_ para establecer un punto inicial de comparación. A partir de ahi, se buscara mejorar los resultados medante la implementación de diversos modelos, optimizacion de hiperparámetros y _feature engineering_.

# Selección del dataset

En el dataset elegido se busca predecir si un individuo presenta rasgos **extrovertidos** o **introvertidos** a partir de caracteristicas de comportamiento social del mismo.

El dataset tiene tanto variables categoricas como numericas lo cual permite aplicar técnicas de preprocesamiento y codificación.

El dataset elegido se saco de una competencia de Kaggle, el mismo se puede encontrar en [este link](https://www.kaggle.com/competitions/playground-series-s5e7/data?select=train.csv).

# Importanción de librerias

Se importan las distintas librerias que seran utilizadas durante el trabajo práctico.
"""

import plotly.express as px
import pandas as pd
import seaborn as sbn
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import TargetEncoder
from sklearn.metrics import (accuracy_score, f1_score, roc_auc_score,classification_report, confusion_matrix)
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
import xgboost as xgb
from matplotlib.colors import ListedColormap
from matplotlib.colors import ListedColormap, LinearSegmentedColormap
import numpy as np
from sklearn.metrics import roc_curve

"""# Carga de información en Dataframes"""

import pandas as pd
df = pd.read_csv('train.csv')
df

"""## Primer vistazo de los datos"""

df.shape #cantidad de observaciones y atributos

df.info() #paneo general de las columnas y su tipo de dato

df.describe()

df.isnull().sum() #cantidad de nulos por atributo

"""Se puede notar que hay columnas las cuales cuentan con valores nulos, las mismas seran trabajadas durante el análisis exploratorio de datos.

Se busca si hay alguna observación duplicada, ya que en caso de que exista si esta en el set de entrenamiento y luego en el de testeo, por ejemplo, esto podria hacer que el modelo se la aprenda y que despues haga "trampa".
"""

df.duplicated().sum()

"""Vemos que no existen observaciones duplicadas por lo que no hay que eliminar ninguna observación en principio.

# Separación del dataset

## Separación de la variable a predecir
"""

features = df.drop("Personality",axis=1)
target = df['Personality']

features

target

"""## Division en Train, Validation y Test"""

from sklearn.model_selection import train_test_split

diez_porciento = round(len(features) / 10)

f_train, f_test, t_train, t_test = train_test_split(features, target, test_size=diez_porciento, random_state=24)

f_train, f_validation, t_train, t_validation = train_test_split(f_train, t_train, test_size=diez_porciento, random_state=24)

"""Para que sea mas sencillo el analisis de datos se vuelve a juntar el ```f_train``` y ```t_train```.


"""

df_train = pd.concat([f_train, t_train], axis=1)

#Establezco que extrovertido sera la clase 0 e introvertido la clase
t_train_num = t_train.map({'Extrovert': 0, 'Introvert': 1})
t_validation_num = t_validation.map({'Extrovert': 0, 'Introvert': 1})
t_test_num = t_test.map({'Extrovert': 0, 'Introvert': 1})

"""# Análisis exploratorio de datos"""

df_train

"""Lo primero que se puede notar es que la columna ```id``` no aporta información relevante, la misma lo unico que hara es generar ruido. Este no es mas que un indice para la observación, por lo tanto se eliminara, ya que no aporta información valiosa para nuestro modelo.

Cada vez que se elimine alguna feature del set de entrenamiento tambien se lo debera hacer en el de validación y en el de test. Lo mismo ocurrira en el caso de agregar alguna feature o hacer algun tipo de modificación sobre alguna columna.


"""

df_train.drop(columns='id',inplace=True)
f_validation.drop(columns='id',inplace=True)
f_test.drop(columns='id',inplace=True)

"""Ahora si, el dataset contiene **8 variables predictoras** (features) y **1 variable objetivo** (target).

## El target: ```Personality```

Es una variable categorica binaria que indica si una persona es ```Extrovert``` o ```Introvert```. Como ya se menciona en el titulo, es la variable a predecir.

Se analiza al target para ver si sera o no necesario un balanceo de los datos.
"""

colores = {
    'Extrovert': '#239B75',
    'Introvert': '#D66037'
}

cantidades_target = df_train['Personality'].value_counts().reindex(['Extrovert', 'Introvert'])

plt.figure(figsize=(6, 6))
plt.pie(cantidades_target,
        labels=['Extrovertido','Introvertido'],
        autopct='%1.1f%%',
        colors=[colores['Extrovert'], colores['Introvert']],
        startangle=90)
plt.title('Distribución del target (Personalidad)')
plt.show()

"""Este grafico muestra que el dataset tiene aproximdamente el 74% de las observaciones las cuales pertenecen a personas extrovertidas y solo el 26% pertenece a introvertidas.

## Variables númericas

Se cuenta con 5 variables numéricas:
- Time_spent_Alone
- Social_event_attendance
- Going_outside
- Friends_circle_size
- Post_frequency
"""

columnas_numericas = ['Time_spent_Alone', 'Social_event_attendance', 'Going_outside','Friends_circle_size', 'Post_frequency']
df_train.loc[:,columnas_numericas].describe().T[['min','max']]

"""Se puede notar que todas las variables tienen escalas acotadas pero de distintas magnitudes. Por lo tanto lo que se hara es normalizarlos, pero antes se hara la imputación de nulos, ya que como se vio al principio, algunas de las variables los poseen."""

df_train[columnas_numericas].isnull().sum()

"""### Variables y su relacion con el target

Para tener una idea de por donde rondan los valores de la variable según a que categoria pertenecen.

#### ```Time_spent_Alone```

Representa la cantidad de horas que una persona pasa sola.

Relación entre ```Time_spent_Alone``` (tiempo que pasa solo) y el target ```Personality```.
"""

plt.figure(figsize=(6, 5))
sbn.boxplot(data=df_train, x='Personality', y='Time_spent_Alone',
            palette={'Extrovert': '#1D9E75', 'Introvert': '#D85A30'})
plt.title('Tiempo pasado solo según personalidad')
plt.xlabel('Personalidad')
plt.ylabel('Tiempo solo')
plt.show()

"""Como se puede ver en el grafico, esta variable tiene una correlacion negativa con el target, es decir, a mayor tiempo pasado solo, mayor probabilidad de ser introvertido.

En el boxplot se puede ver que los introvertidos tienen valores mas altos que los extrovertidos

#### ```Social_event_attendance```

Mide con que frecuencia una persona asiste a eventos sociales.

Relación entre ```Social_event_attendance``` (asistencia a eventos sociales) y el target ```Personality```.
"""

plt.figure(figsize=(6, 5))
sbn.boxplot(data=df_train, x='Personality', y='Social_event_attendance',
            palette={'Extrovert': '#1D9E75', 'Introvert': '#D85A30'})
plt.title('Asistencia a eventos sociales')
plt.xlabel('Personalidad')
plt.ylabel('Asistencia a eventos sociales')
plt.show()

"""En el boxplot se puede ver como los extrovertidos asisten a significativamente mas eventos sociales que los introvertidos.

#### ```Going_outside```

Esta variable indica la frencuencia con la que una persona sale de su casa (no necesariamente para ver gente, puede ser ir al supermercado o ir a caminar solo/a).

Relación entre ```Going_outside``` (salir de la casa) y el target ```Personality```.
"""

plt.figure(figsize=(6, 5))
sbn.boxplot(data=df_train, x='Personality', y='Going_outside',
            palette={'Extrovert': '#1D9E75', 'Introvert': '#D85A30'})
plt.title('Salidas de la casa')
plt.xlabel('Personalidad')
plt.ylabel('Frecuencia de salidas')
plt.show()

"""Nuevamente el grafico muestra que los extrovertidos salen com mayor frecuencia que los introvertidos. En este caso podemos ver que la variable se correlaciona positivamente con el target.

#### ```Friends_circle_size```

Representa el tamaño del circulo de amigos de una persona.

Relación entre ```Friends_circle_size``` (tamaño del grupo de amigos) y el target ```Personality```.
"""

plt.figure(figsize=(6, 5))
sbn.boxplot(data=df_train, x='Personality', y='Friends_circle_size',
            palette={'Extrovert': '#1D9E75', 'Introvert': '#D85A30'})
plt.title('Tamaño del círculo de amigos')
plt.xlabel('Personalidad')
plt.ylabel('Tamaño del círculo de amigos')
plt.show()

"""El boxpot muestra que los extrovertidos tienden a tener circulos de amigos mas grandes que los introvertidos. Podemos notar tambien que hay bastantes outliers para los introvertidos.

#### ```Post_frequency```

Mide la frecuencia con la que una persna publica contenido en las redes sociales.

Relación entre ```Post_frequency``` (frecuencia con la que se hace un posteo en redes sociales) y el target ```Personality```.
"""

plt.figure(figsize=(6, 5))
sbn.boxplot(data=df_train, x='Personality', y='Post_frequency',
            palette={'Extrovert': '#1D9E75', 'Introvert': '#D85A30'})
plt.title('Frecuencia de publicaciones en redes sociales')
plt.xlabel('Personalidad')
plt.ylabel('Frecuencia de publicaciones')
plt.show()

"""Los extrovertidos publican mas frecuentemente que los introvertidos, lo cual es consistente ya que se supone que los extrovertidos tienen mayor actividad social.

Se decide no eliminar los outliers ya que al ser una encuesta puede suceder que haya personas que sean "distintas" al resto de las de su misma clase y eso no esta mal.Es decir, le puede servir al modelo saber que existen estos casos aunque sean muy escasos.

### Relación entre variables y su categoria

Cruce entre **tamaño del grupo de amigos** y **tiempo que pasa solo**.
"""

fig1 = px.scatter(
    df_train.groupby(['Friends_circle_size', 'Time_spent_Alone', 'Personality']).size().reset_index(name='counts'),
    x="Friends_circle_size",
    y="Time_spent_Alone",
    size="counts",
    color="Personality",
    color_discrete_map=colores,
    opacity=0.6,
    title="Relación: Tamaño Círculo vs Tiempo Solo (Densidad)"
)
fig1.show()

"""En este grafico se cruza en el eje x el tamaño del circulo de amigos y en el eje y el tiempo que pasa solo, el tamaño del circulito representa la cantidad de personas con esa combinacion de valores. Y el color indica la personalidad.


Se puede observar una **muy clara separación entre ambas clases**. Los extrovertidos se concentran en la region en donde tienen una gran cantidad de amigos y bajo tiemposolos. Por otro lado, los introvertidos se acumulan en el cuadrante opuesto en el que tienen menor cantidad de amigos y mucho tiempo solos.

Tambien se puede notar que el tamaño de los puntos es mayor para los extrovertidos, esto ya que el dataset presentaba mayor cantidad de observaciones para esta clase, esto se va a repetir para el resto de las observaciones tambien.

Cruce entre **tiempo solo** y su relación con la **vida social**
"""

fig2 = px.scatter(
    df_train.groupby(['Social_event_attendance', 'Time_spent_Alone', 'Personality']).size().reset_index(name='counts'),
    x="Social_event_attendance",
    y="Time_spent_Alone",
    size="counts",
    color="Personality",
    color_discrete_map=colores,
    opacity=0.6,
    title="Relación: Asistencia a Eventos vs Tiempo Solo (Densidad)"
)
fig2.show()

"""Este grafico tiene un patron parecido al anterior. Se vuelve a reforzar la hipotesis de que los extrovertidos combinan una alta asistencia a eventos sosciales con poco tiempo solos, mientras que los introvertidos muestran lo contrario.

Relación entre **salidas** y **frecuencia de posteo**
"""

fig3 = px.scatter(
    df_train.groupby(['Going_outside', 'Post_frequency', 'Personality']).size().reset_index(name='counts'),
    x="Going_outside",
    y="Post_frequency",
    size="counts",
    color="Personality",
    color_discrete_map=colores,
    opacity=0.6,
    title="Relación: Salidas vs Frecuencia de Posteo (Densidad)"
)
fig3.show()

"""En este podemos ver que los introvertidos se concentran mucho mas.

### Imputación de valores nulos

Voy a imputar los datos con la **mediana de los mismos**, para calcular la misma se quitaran primero los valores de los outliers para que no generen ruido en la imputación de datos.

Se imputaran tanto en el set de entrenamiento como en el de validacion y test.

Antes de imputar a los valores, se hacen ```indicadores de nulos```, esto es para que el modelo pueda distinguir o hallar algun patron.
"""

columnas_numericas

for columna in columnas_numericas:
  df_train[f'{columna}_era_nula'] = df_train[columna].isnull().astype(int)
  f_validation[f'{columna}_era_nula'] = f_validation[columna].isnull().astype(int)
  f_test[f'{columna}_era_nula'] = f_test[columna].isnull().astype(int)

def calcular_valores_imputacion_generales(df_train,features):
  medianas = {}

  for feature in features:
    #hallo la mediana sin contar los outliers, digo que es un outlier si esta a mas de dos desviaciones estandar.
    media = df_train[feature].mean()
    std = df_train[feature].std()

    #filtro outliers para calcular mediana sin que generen ruido
    df_sin_outliers = df_train[(df_train[feature] >= media - 2 * std)&(df_train[feature] <= media + 2 * std)]

    #calculo mediana
    mediana = df_sin_outliers[feature].median()
    medianas[feature] = mediana

  return medianas

def imputar_valores_numericos(df,medianas):
  for feature,mediana in medianas.items():
    df[feature] = df[feature].fillna(mediana)

#Calculo las medianas generales para
medianas_general = calcular_valores_imputacion_generales(df_train,columnas_numericas)

#Imputo los valores nulos en todos los sets de datos
imputar_valores_numericos(f_validation, medianas_general)
imputar_valores_numericos(f_test, medianas_general)

def calcular_medianas_por_clase(df_train, features):
    medianas = {}

    for feature in features:
        medianas[feature] = {}

        for clase in df_train["Personality"].unique(): #para que sea reproducible

            grupo = df_train[df_train["Personality"] == clase]

            media = grupo[feature].mean()
            std = grupo[feature].std()

            grupo_filtrado = grupo[ (grupo[feature] >= media - 2 * std) &(grupo[feature] <= media + 2 * std)]

            medianas[feature][clase] = grupo_filtrado[feature].median()

    return medianas

def imputar_por_clase(df, medianas):
    for feature in medianas.keys():
        for clase, mediana in medianas[feature].items():
            df.loc[(df["Personality"] == clase) &(df[feature].isna()),feature] = mediana

#Para el set de entramiento se imputara segun si son extrovertidos o introvertidos ya que contamos
#con esa información, ademas sabemos que NO CONTAMOS CON NULOS EN ESA COLUMNA
medianas_por_clase = calcular_medianas_por_clase(df_train, columnas_numericas)
imputar_por_clase(df_train, medianas_por_clase)

"""### Normalización de valores

Ahora si se normalizan los datos.
Se hace```fit``` unicamente con el ```f_train```, ya que queremos que los datos se adapten a este. Luego para ```f_validation``` y ```f_test``` se les aplica ```transform```.
"""

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

#se entrena y transforma al set de entrenamiento
df_train.loc[:,columnas_numericas] = scaler.fit_transform(df_train[columnas_numericas])

#se transforman el set de validacion y test, en el mismo se usa el min/max que se aprendio
#en el test
f_validation.loc[:, columnas_numericas] = scaler.transform(f_validation[columnas_numericas])
f_test.loc[:, columnas_numericas] = scaler.transform(f_test[columnas_numericas])

"""Se analiza si existe alguna correlación entre las variables numericas."""

plt.figure(figsize=(8, 6))
corr = df_train[columnas_numericas].corr()
sbn.heatmap(corr, annot=True, cmap='coolwarm', center=0, fmt='.2f')
plt.title('Correlación entre variables numéricas')
plt.show()

"""Se puede ver que las variables ```Social_event_attendance```, ```Going_outside```, ```Friends_circle_size``` y ```Post_frequency``` presentan correlaciones positivas entre si. Mientras que ```Time_spent_Alone``` tiene correlacion negativa con el resto de variables.

Esto es algo que se podia intuir de los boxplots.

## Variables categóricas
"""

columnas_categoricas = ['Drained_after_socializing','Stage_fear']

pd.crosstab(df_train['Stage_fear'], df_train['Personality'], normalize='index').round(3)

pd.crosstab(df_train['Drained_after_socializing'], df_train['Personality'], normalize='index').round(3)

"""Respecto a ```Stage_fear``` es una bariable binaria que indica si la persona tiene miedo escenico.

Y sobre ```Drained_after_socializing``` es tambien una variable binaria que infica si la persona se siento emocionalmente agotada despues de interactual socialmente.
"""

fig, axes = plt.subplots(1, 2, figsize=(10, 5))
columnas = ['Stage_fear', 'Drained_after_socializing']

for ax, col in zip(axes, columnas):
    ct = pd.crosstab(df_train[col], df_train['Personality'], normalize='index')

    lista_colores_grafico = [colores[c] for c in ct.columns]

    ct.plot(kind='bar', stacked=True, ax=ax, color=lista_colores_grafico, rot=0)

    ax.set_title(f'{col} vs Personality')
    ax.set_ylabel('Proporción')
    ax.set_xlabel('')
    ax.legend(title='Personality')

plt.tight_layout()
plt.show()

"""Para ```Stage_fear``` cuando la respuesta es ```No```, la gran maypria de los casos son extrovertidos, cuando la respuesta es ```Yes```, la proporción se invierte. Despues la categoria ```Unknown``` se muestra mas cercano al patron de ```Yes``` lo que puede servirle al modelo para darle informacion sobre el encuestado.

Luego, para ```Drained_after_socializing``` sucede algo parecido. Quienes responden ```No``` son en su mayoria extrovertidos y los que responden ```Yes``` son en gran parte introvertidos.

**Estas dos variables tienen un poder bastante claro para distinguir entre extrovertidos e introvertidos**.

Respecto a los nulos:
"""

df_train[columnas_categoricas].isnull().sum()

"""Antes de imputar a los valores, se hacen ```indicadores de nulos```, esto es para que el modelo pueda distinguir o hallar algun patron.


"""

for columna in columnas_categoricas:
  df_train[f'{columna}_era_nula'] = df_train[columna].isnull().astype(int)
  f_validation[f'{columna}_era_nula'] = f_validation[columna].isnull().astype(int)
  f_test[f'{columna}_era_nula'] = f_test[columna].isnull().astype(int)

"""A los valores nulos se los imputara con el valor ```Unknown``` ya que se considera que si no respondieron tenian alguna razon para hacerlo.

Se podria tomar la decisión de inferirlo segun que contesto en la otra categoria, pero seria inconsistente en el caso en el que no se tenga ninguna de las dos.


"""

for columna in columnas_categoricas:
  df_train[columna] = df_train[columna].fillna('Unknown')
  f_validation[columna] = f_validation[columna].fillna('Unknown')
  f_test[columna] = f_test[columna].fillna('Unknown')

for columna in columnas_categoricas:
    print(f"\n{columna} — target cuando la respuesta era nula:")
    print(df_train[df_train[f'{columna}_era_nula'] == 1]['Personality']
          .value_counts(normalize=True).round(3))

"""Como se menciono previamente, se puede ver que cuando ```Drained_after_socializing ``` es nulo, sube la proporción de introvertidos. Esto confirma la teoria de que no responder la pregunta *da información*.

# Feature Engineering

En esta sección se crearan nuevas features a partir de las variables ya existentes, esto para darle al modelo mayor información del comportamiento de cada persona.

Las variables que se van a mostrar surgieron de que durante el análisis exploratorio de datos, las variables numericas mostraron correlaciones entre si.

## ```Social_score```

En cuanto a las features numéricas, como ya se vio previamente, a excepción de ```Time_spent_Alone``` la cual tiene correlación negativa, las otras 4 variables se encuentran correlacionadasm positivamente entre si.

Esto sugiere que las personas mas extrovertidas tienden a salidar mas, a tener mas amigos, asistir a mas eventos, postear mas y que ademas pasan menos tiempo solas.

Por esto se determino hacer una nueva feature llamada ```social_score``` que tiene la información de estas 5 variables en una sola. En la misma se **sumaran** las cuatro variables con correlación alta y se **restara** la que tenia correlación negativa.

Esto le va a dar al modelo un *resumen* de las features.
"""

df_train['social_score'] = (df_train['Social_event_attendance'] + df_train['Going_outside'] + df_train['Friends_circle_size'] + df_train['Post_frequency']) - df_train['Time_spent_Alone']
f_validation['social_score'] = (f_validation['Social_event_attendance'] + f_validation['Going_outside'] + f_validation['Friends_circle_size'] + f_validation['Post_frequency']) - f_validation['Time_spent_Alone']
f_test['social_score'] = (f_test['Social_event_attendance'] + f_test['Going_outside'] + f_test['Friends_circle_size'] + f_test['Post_frequency']) - f_test['Time_spent_Alone']

"""Al sumar las cuatro variables positivas y restar la negativa, obtenemos una variable que crece cuando una persona es socialmente mas activa y decrece cuando pasa mas tiempo sola.

Esta variable puede tomar valores dentro del intervalo ```[-1,4]```, ya que:
- Minimo : las 4 positivas en 0 y la negariva en 1 -> ```(0+0+0+0)-1 = -1```.
- Máximo : las 4 positivas en 1 y la negariva en 0 -> ```(1+1+1+1)-0 = 4```.

Al igual que en las variables numéricas, se normalizaran los valores. Esto para que si despues se usa un modelo basado en distancias o en el gradiente esta columna pesaria mucho mas en el calculo de distancia por su escala, por ejemplo.(Se normalizara al final)

## ```Social_alone_ratio```

Se aprovecha que se tiene información de ```Social_event_attendance``` y ```Time_spent_Alone``` para ver como la persona balancea el socializar y el estar solo.

El la feature ```social_score``` que se creo previamente se obtiene una suma, pero no la **proporción**. Podria existir el caso en el que dos personas tengan el mismo ```social_score``` pero que tengan perfiles muy distintos, una que salga mucho y no este mucho tiempo sola y otra que sale menos pero tambien pase menos tiempo sola.

Para esto se calcula el ratio: ```Social_event_attendance / (time_spent_Alone+1)```.

Se le pone el ```+1``` ya que sino se podria tener una división por cero(ya que ```time_spent_alone``` puede valer 0).
"""

df_train['social_alone_ratio'] = df_train['Social_event_attendance'] / (df_train['Time_spent_Alone'] + 1)
f_validation['social_alone_ratio'] = f_validation['Social_event_attendance'] / (f_validation['Time_spent_Alone'] + 1)
f_test['social_alone_ratio'] = f_test['Social_event_attendance'] / (f_test['Time_spent_Alone'] + 1)

"""Un valor alto de este ratio indica que la persona asiste a muchos eventos sociales en realcion al tiempo que pasa sola, es decir, que tiene un perfil mas *extrovertido*. Un valor mas cercano a 0 indicaria lo contrario.

## ```n_missing_answers```

Durante el análisis exploratorio de datos se crearon las columnas ```_era_nula```para indicuar cuando a una observación se le imputo alguna variable.

Se creara una nueva feature que contenga la cantidad de nulos que tenia esa observación ya que al modelo le podria resultar util saber que una persona no contesto casi nada por ejemplo.

Basicamente, la hipótesis es que las personas que no respondieron muchas preguntas podrian tener un patron distinto a quienes si respondieron todo.
"""

columnas_era_nula = [col for col in df_train.columns if col.endswith('_era_nula')]
df_train['n_missing_answers'] = df_train[columnas_era_nula].sum(axis=1)
f_validation['n_missing_answers'] = f_validation[columnas_era_nula].sum(axis=1)
f_test['n_missing_answers'] = f_test[columnas_era_nula].sum(axis=1)

"""## Normalización de nuevas features

Como ya se menciono previamente, se normalizaran los valores de las columnas numéricas para que el modelo le de el mismo peso a todas en caso de que sea un modelo que utilice distancias o el gradiente, por ejemplo.

Las tres nuebas feaures numericas se van a normalizar con ```MinMaxScaler```.
"""

nuevas_features = ['social_score', 'social_alone_ratio','n_missing_answers']

scaler_fe = MinMaxScaler()
df_train[nuevas_features] = scaler_fe.fit_transform(df_train[nuevas_features])
f_validation[nuevas_features] = scaler_fe.transform(f_validation[nuevas_features])
f_test[nuevas_features] = scaler_fe.transform(f_test[nuevas_features])

"""## Eliminación del target en df_train"""

f_train = df_train.drop(columns='Personality')

"""# Codificación de variables categoricas

Las variables categóricas no pueden ser ingresadas directamente a los modelos de *Machine Learning*, ya que estos operan unicamente sobre valores numericos.

Por lo tanto, es necesario transformar estas variables categoricas en representaciones numericas.

## ```Stage_fear```

La variable ```Stage_fear``` tiene 3 categorias: ```Yes```,```No``` y ```Unknown```. Las mismas no tienen ningun orden entre ellas (osea no tendria sentido decir, por ejemplo, que ```Unknow``` esta entre ```Yes``` y ```No```).

En este caso se encodeara a la feature utilizando ```One Hoy Encoding```, tenemos una cardinalidad baja ya que solo son 3 categorias, y la idea es que no se asuma ninguna relación de orden entre las mismas.

El **One Hot Encoding** sirve para tranasformar una variable que es categorica en tantas columnas binarias como valores tenga. Cada columna indica si la observación pertenece o no a esa categoria (1 si pertenece). Ademas esta bueno ya que no impone ningun orden entre las distintas categorias.
"""

ohe_stage_fear = OneHotEncoder(handle_unknown='ignore')
"""
Obs: vi que en clase se usaba el drop='first' que lo que haria seria que si todas estan en 0 se infiere que formaba parte
de la categoria que no tiene columna, en este caso utilice el handle_unknown='ignore' que es para que si en f_validation o f_test aparece una categoria nueva
que no existia en train, el encoder ponga en 0 a todas y que signifique que no pertenecia a ninguna categoria existente en el set de entrenamiento.
Esto no deberia ocurrir pero por las dudas.
"""

encoded_stage_fear_train = ohe_stage_fear.fit_transform(f_train[['Stage_fear']]).todense().astype(int)

encoded_stage_fear_validation = ohe_stage_fear.transform(f_validation[['Stage_fear']]).todense().astype(int)
encoded_stage_fear_test = ohe_stage_fear.transform(f_test[['Stage_fear']]).todense().astype(int)

# obtiene las columnas que tengan 'Stage_fear' y les agrega la categoria
columnas_stage_fear = ohe_stage_fear.get_feature_names_out(['Stage_fear'])

#Se convierten en dfs
df_encoded_train = pd.DataFrame(encoded_stage_fear_train, columns=columnas_stage_fear, index=f_train.index)
df_encoded_validation = pd.DataFrame(encoded_stage_fear_validation, columns=columnas_stage_fear, index=f_validation.index)
df_encoded_test = pd.DataFrame(encoded_stage_fear_test, columns=columnas_stage_fear, index=f_test.index)

#se concatenan a los dfs
f_train = pd.concat([f_train, df_encoded_train], axis=1)
f_validation = pd.concat([f_validation, df_encoded_validation], axis=1)
f_test = pd.concat([f_test, df_encoded_test], axis=1)

# Se eliminan las columnas originales ya que los modelos comen numeros no strings
f_train.drop(columns='Stage_fear', inplace=True)
f_validation.drop(columns='Stage_fear', inplace=True)
f_test.drop(columns='Stage_fear', inplace=True)

"""## ```Drained_after_socializing```

Esta feature tambien tiene 3 categorias, pero en este caso en vez de crear 3 columnas binarias se comprimira en **una unica columna númerica** en donde cada categoría se va a reemplazar por la tasa de introvertidos observada en el set de entrenamiento para esa categoria.

Para esto se utilizara ```sklearn.preprocessing.TargetEncode```, el cual a momento de entrenar dividira el ```f_train``` en folds ,calculara la media del target con los folds restantes y encodea cada fila sin que *vea* su propio target.

Lo que se menciono anteriormente de **Target Encoding** es un tipo de **Mean Encoding**.
"""

te = TargetEncoder(target_type='binary', smooth='auto', random_state=24)

f_train['Drained_after_socializing'] = te.fit_transform(f_train[['Drained_after_socializing']], t_train_num).ravel()

f_validation['Drained_after_socializing'] = te.transform(f_validation[['Drained_after_socializing']]).ravel()

f_test['Drained_after_socializing'] = te.transform(f_test[['Drained_after_socializing']]).ravel()

#Para ver que valor se le asigno a cada categoria
dict(zip(te.categories_[0], te.encodings_[0]))

"""Se puede observar que la categoria ```Unknown``` queda mucho mas cerca de ```Yes``` que de ```No```, anteriormente habiamos relacionado a las personas que respondian ```Yes``` con ser introvertidas, ahora se estaria dando a entender que si no responden tambien podria estar relacionado con esto.

# Métrica a utilizar

## Planteo de metrica y código a utilizar

Primero que nada durante el analsis exploratorio de datos se observo que las features ```Stage_fear``` y ```Drained_after_socializing``` funcionaban como predictoras muy buenas.

Con el desbalance que hay de ```74% Extrovert``` y ```26% Introvert```, si se utilizaria ```accuracy``` como metrica un modelo que siempre prediga ```Extrovert``` ya tendria un ```74%``` de ```accuracy``` sin haber aprendido nada.

Como métrica principal para comparar los modelos y buscar hiperparámetros se utilizara ```F1-score``` para la clase ```Introvert``` que es la clase con menores observaciones dentro del set de entrenamiento.

La métrica ```F1``` combina precision y recall(las cuales son análogas) y calculandolo sobre la clase minoritaria (```Introvert```) asegura que el modelo efectivamente esta aprendiendo a distinguir a los ```Introvertidos``` y no es que simplemente esta apostando a la clase mayoritaria.

De igual manera voy a mostrar la ```Accuracy``` ya que sirve de referencia y resulta mas intuitiva.

Tambien se hara mencion a ```ROC-AUC``` que es util para comprar modelos. Y la```matriz de confusion``` que muestra en que se equivoca el modelo.

Para no repetir código se haran las funciones que calculen lo mencionado anteriormente, para asi no repetirlo en cada modelo.
"""

def evaluar_metricas_modelo(modelo,features,prediccion,target_verdadera,nombre_modelo,num_iteracion):
  prob_target = modelo.predict_proba(features)[:,1]

  print(f"=== {nombre_modelo} === {num_iteracion} ===\n")
  print(f"Accuracy : {accuracy_score(target_verdadera, prediccion):.4f}\n")
  print(f"F1-score : {f1_score(target_verdadera, prediccion):.4f}\n")
  print(f"ROC-AUC  : {roc_auc_score(target_verdadera, prob_target):.4f}\n")

  print("Metricas por clase:")
  print(classification_report(target_verdadera, prediccion, target_names=['Extrovert', 'Introvert']))

  cm = confusion_matrix(target_verdadera, prediccion)

  fig, ax = plt.subplots(figsize=(6, 6))

  heatmap = sbn.heatmap(cm, annot=True, fmt='d', cmap='Blues',
              xticklabels=['Extrovert', 'Introvert'],
              yticklabels=['Extrovert', 'Introvert'],
              cbar_kws={'label': 'Cantidad'},
              ax=ax)

  ax.set_yticklabels(ax.get_yticklabels(), rotation=0)
  cbar = heatmap.collections[0].colorbar
  cbar.set_label('Cantidad', rotation=0, labelpad=20, va='center')

  plt.suptitle(f'Matriz de confusión - {nombre_modelo}', fontsize=16, fontweight='bold', y=0.98)
  ax.set_title(f'{num_iteracion}', fontsize=12, pad=20) # Usamos ax.set_title para mayor precisión

  ax.set_ylabel('Real', rotation=0, labelpad=40, va='center', fontsize=12)
  ax.set_xlabel('Predicho', fontsize=12)

  plt.tight_layout(rect=[0, 0.03, 1, 0.95])
  plt.show()

"""## Desglose de métrica seleccionada (F1-score)

Como ya se dijo previamente **F1-score** es una metrica que usa **precisión** y **recall**.
- Precisión: de todos los casos que el modelo predijo como Introvert, cuantos realmente lo eran.
- Recall : de todos los casos que realmente eran Introvert, cuantos detecto el modelo correctamente.

El **F1-score** es una medida que combina ambas:

 $$F1 = 2 \cdot \frac{Precision \cdot Recall}{Precision + Recall}$$

 Esta metrica penaliza cuando una de las dos metricas (Precision o Recall) es muy baja. Es decir, obligara al modelo a ser bueno en ambas al mismo tiempo.

## ¿ Por que F1 sobre la clase Introvert?

Se calcula el F1-score especificamente sobre la clase **Introvert** por ser la clase minoritaria y por lo tanto la mas dificil de predecir. Un modelo que aprenda a identificar bien a los introvertidos necesariamente aprende a distinguir entre las dos clases.

Es decir, si el F1 sobre Introvert es alto, significa que el modelo:
- No esta clasificando introvertidos como extrovertidos (buen recall).
- Cuando dice que alguien es introvertido, tiene razon (buena precisión).

Esto garantiza que el modelo realmente aprendio a separar las clases y no esta explotando el desbalance (osea ir siempre a la mayoritaria).

## Métricas complementarias

Si bien el **F1-score sobre Introvert** es la métrica seleccionada como la principal para comparar y tomar decisiones.
Tambien se mostraran:

- Accuracy: sirve para tener una intuicion rapida del comportamiento del modelo.
- ROC-AUC : mide la capacidad que tiene el modelo a lo largo de todos los puntos d corte de decision.
- Matriz de confusión: va a permitir ver en que tipo de error se equivoca el modelo.

# Baseline - Regresión Logística

Como ```Baseline``` se utilizara un modelo de ```Regresión Logística```, el mismo es un modelo lineal.

Para la busqueda de hiperparámetros se utilizara el metodo de ```Grid Search``` el cual va a probar cada combinación posible y va a quedarse con el que tenga la mejor metrica.
"""

parametros_grid_baseline_1 = {"C" : [0.0001, 0.001, 0.01, 0.1, 1, 10, 100]}

grid_baseline_1 = GridSearchCV(
    estimator=LogisticRegression(class_weight='balanced', max_iter=1000, random_state=24),
    param_grid=parametros_grid_baseline_1,
    scoring='f1',
    cv=5,
    n_jobs=-1
)

grid_baseline_1.fit(f_train, t_train_num)

print("Mejor C:", grid_baseline_1.best_params_)
print("F1 promedio en CV:", grid_baseline_1.best_score_.round(4))

modelo_baseline_1 = grid_baseline_1.best_estimator_

prediccion_baseline_validation_1 = modelo_baseline_1.predict(f_validation)

resultados_baseline = evaluar_metricas_modelo(modelo_baseline_1, f_validation, prediccion_baseline_validation_1,t_validation_num, "Baseline - Regresión Logística",'Primera iteración')

"""Ajusto acercandome mas al primer hiperparametro que gano."""

parametros_grid_baseline_2 = {"C" : [0.002,0.003,0.004,0.005,0.006,0.007,0.008,0.009,0.01,0.02,0.03,0.04,0.05,0.06,0.07,0.08,0.09]}

grid_baseline_2 = GridSearchCV(
    estimator=LogisticRegression(class_weight='balanced', max_iter=1000, random_state=24),
    param_grid=parametros_grid_baseline_2,
    scoring='f1',
    cv=5,
    n_jobs=-1
)

grid_baseline_2.fit(f_train, t_train_num)

print("Mejor C:", grid_baseline_2.best_params_)
print("F1 promedio en CV:", grid_baseline_2.best_score_.round(4))

modelo_baseline_2 = grid_baseline_2.best_estimator_

prediccion_baseline_validation_2 = modelo_baseline_2.predict(f_validation)

resultados_baseline = evaluar_metricas_modelo(modelo_baseline_2, f_validation, prediccion_baseline_validation_2,t_validation_num, "Baseline - Regresión Logística",'Segunda iteración')

"""Me quedo con el ```modelo_baseline_2``` que es el que resulto tener mayor ```score```."""

modelo_baseline = modelo_baseline_2
prediccion_baseline_validation = prediccion_baseline_validation_2

"""### Explicación de matriz de confusión

Si bien todas las metricas planteadas fueron utilizadas para ajustar hiperparametros, fueron a vista.

En este caso se va a explayar la matriz de confusion del ```modelo_baseline_2```.

En total el set de validación tiene 1384 extrovertidos reales y 468 introvertidos reales.

En la matriz tenemos:
- 1361 verdaderos negativos: el modelo predijo *Extrovert* y la persona realmente era extrovertida. Es la celdra que mas observaciones tiene lo cual es esperable porque los extrovertidos son la clase mayoritaria.
- 443 verdaderos positivos: el modelo predijo *Introvert* y la persona realmente era negariva. De los 468 introvertidos del set de validación, el modelo detecto correctamente a 443 del mismo. Este es un resultado que consideramos valioso porque la clase introvertida es la minoritaria y la que seria *mas dificil de predecir*.

- 23 falsos positivos: a los que el modelo los predijo como *Introvertidos* pero en realidad eran extrovertidos-

-25 falsos negativos: el modelo predijo *extrovertido* cuando en realidad eran introvertidos, es un error importante, son los introvertidos que el modelo no logro detectar.

# Random Forest

Como primer modelo se utilizara ```Random Forest``` que es un modelo de ensamble basado en arboles. En este caso como son mas hiperparámetros y se deben hacer mas combinaciones se utilizara ```Randomized Search``` el cual prueba combinaciones al azar en vez de todas.
"""

param_dist_rf_1 = {
    'n_estimators': [50, 100, 200, 500],
    'max_depth': [None, 5,10, 20, 30, 40],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1,2,3,5, 10, 15],
    'max_features': ['sqrt', 'log2'],
    'class_weight': ['balanced', None]
}

rf_1 = RandomForestClassifier(random_state=24)

random_search_rf_1 = RandomizedSearchCV(
    estimator=rf_1,
    param_distributions=param_dist_rf_1,
    n_iter=100,
    scoring='f1',
    cv=5,
    random_state=24,
    n_jobs=-1
)

random_search_rf_1.fit(f_train, t_train_num)

print("Mejores hiperparámetros:", random_search_rf_1.best_params_)
print("F1 promedio en CV:", random_search_rf_1.best_score_.round(4))

modelo_rf_1 = random_search_rf_1.best_estimator_

prediccion_rf_validation_1 = modelo_rf_1.predict(f_validation)

resultados_rf_1 = evaluar_metricas_modelo(modelo_rf_1, f_validation, prediccion_rf_validation_1, t_validation_num, "Modelo 1 - Random Forest",'Primera iteración')

"""Da major para el set de entrenamiento que para el de validación, por lo que puede estar haciendo overfitting. Se baja la profunidad maxima y se permiten hojas mas grandes.

Como se puede notar, aumentando el tamaño minimo de hojas y la profundidad del arbol mejoro el score del set de validación. Tambien bajo el del set de entrenamiento pero muy poco.
"""

param_dist_rf_2 = {
    'n_estimators': [50, 100, 200, 500],
    'max_depth': [3, 5, 7, 10], #se setea menos profundidad maxima
    'min_samples_split': [10, 20, 30, 50], #hojas mas grandes para evitar overf
    'min_samples_leaf': [1,2,3,5, 10, 15],
    'max_features': ['sqrt'],
    'class_weight': ['balanced', None]
}

rf_2 = RandomForestClassifier(random_state=24)

random_search_rf_2 = RandomizedSearchCV(
    estimator=rf_2,
    param_distributions=param_dist_rf_2,
    n_iter=100,
    scoring='f1',
    cv=5,
    random_state=24,
    n_jobs=-1
)

random_search_rf_2.fit(f_train, t_train_num)

print("Mejores hiperparámetros:", random_search_rf_2.best_params_)
print("F1 promedio en CV:", random_search_rf_2.best_score_.round(4))

modelo_rf_2 = random_search_rf_2.best_estimator_

prediccion_rf_validation_2 = modelo_rf_2.predict(f_validation)

resultados_rf_2 = evaluar_metricas_modelo(modelo_rf_2, f_validation, prediccion_rf_validation_2, t_validation_num, "Modelo 1 - Random Forest",'Segunda iteración')

"""Como veo que resulto, le bajo nuevamente la altura maxima del arbol y unicamente le permito tener hojas mas grandes para ver si de esta manera contraresta el overfitting.

Ademas se aumenta el ```n_estimators```
"""

param_dist_rf_3 = {
    'n_estimators': [300, 500, 700],
    'max_depth': [2, 3, 5, 7], #tambien lo bajo
    'min_samples_split': [30,40,50,60], #mas grandes para evitar overf
    'min_samples_leaf': [5, 10, 15], #mas grande para evitar overf
    'max_features': ['sqrt'],
    'class_weight': ['balanced', None]
}

rf_3 = RandomForestClassifier(random_state=24)

random_search_rf_3 = RandomizedSearchCV(
    estimator=rf_3,
    param_distributions=param_dist_rf_3,
    n_iter=100,
    scoring='f1',
    cv=5,
    random_state=24,
    n_jobs=-1
)

random_search_rf_3.fit(f_train, t_train_num)

print("Mejores hiperparámetros:", random_search_rf_3.best_params_)
print("F1 promedio en CV:", random_search_rf_3.best_score_.round(4))

modelo_rf_3 = random_search_rf_3.best_estimator_

prediccion_rf_validation_3 = modelo_rf_3.predict(f_validation)

resultados_rf_3 = evaluar_metricas_modelo(modelo_rf_3, f_validation, prediccion_rf_validation_3, t_validation_num,  "Modelo 1 - Random Forest",'Tercera iteración')

"""Me quedo con el ```modelo_rf_3``` que es el que resulto tener mayor ```score```."""

modelo_rf = modelo_rf_3
prediccion_rf_validation = prediccion_rf_validation_3

"""# XG Boost

Como segundo modelo se utilizara ```XG Boost```
"""

parametros_xgb_1 = {
    'learning_rate': [0.01, 0.05, 0.1, 0.2, 0.3],
    'max_depth': [3, 5, 7, 10],
    'subsample': [0.6, 0.8, 1.0],
    'colsample_bytree': [0.6, 0.8, 1.0],
    'n_estimators': [50, 100, 200, 300],
    'gamma': [0, 0.1, 0.2, 0.3, 0.4],
    'alpha': [0, 0.01, 0.1, 1, 10],
    'lambda': [0.01, 0.1, 1, 10],
    'objective': ['binary:logistic']
}

xgb_model_1 = xgb.XGBClassifier(
    objective='binary:logistic',
    n_estimators=100,
    learning_rate=0.1,
    max_depth=3,
    random_state=24
)

random_search_xgb_1 = RandomizedSearchCV(
    estimator=xgb_model_1,
    param_distributions=parametros_xgb_1,
    n_iter=30,
    scoring='f1',
    cv=3,
    random_state=24,
    n_jobs=-1
)

random_search_xgb_1.fit(f_train, t_train_num)

print("Mejores hiperparámetros:", random_search_xgb_1.best_params_)
print("F1 promedio en CV:", random_search_xgb_1.best_score_.round(4))

modelo_xgb_1 = random_search_xgb_1.best_estimator_

prediccion_xgb_validation_1 = modelo_xgb_1.predict(f_validation)

resultados_xgb_1 = evaluar_metricas_modelo(modelo_xgb_1, f_validation, prediccion_xgb_validation_1, t_validation_num, "Modelo 2 - XGBoost",'Primera iteración')

"""Bajo profundidad, subo cantidad de arboles simples, ademas pongo el resto de posibles hiperparametros cerca de los resultados del anterior."""

parametros_xgb_2 = {
    'learning_rate': [0.01,0.05], #lo bajo -> mas lento menos overf
    'max_depth': [2,3,4], #bajo
    'subsample': [0.6, 0.7, 0.8],
    'colsample_bytree': [0.5,0.6,0.7], #bajo
    'n_estimators': [300,400,500,700], #lo subo
    'gamma': [0.3, 0.5, 1.0], #penaliza splits
    'alpha': [0.05, 0.1, 0.2],
    'lambda': [1.0, 5.0, 10.0], #subo -> aumenta penalizacion
    'objective': ['binary:logistic']
}

xgb_model_2 = xgb.XGBClassifier(
    objective='binary:logistic',
    n_estimators=100,
    learning_rate=0.1,
    max_depth=3,
    random_state=24
)

random_search_xgb_2 = RandomizedSearchCV(
    estimator=xgb_model_2,
    param_distributions=parametros_xgb_2,
    n_iter=30,
    scoring='f1',
    cv=3,
    random_state=24,
    n_jobs=-1
)

random_search_xgb_2.fit(f_train, t_train_num)

print("Mejores hiperparámetros:", random_search_xgb_2.best_params_)
print("F1 promedio en CV:", random_search_xgb_2.best_score_.round(4))

modelo_xgb_2 = random_search_xgb_2.best_estimator_

prediccion_xgb_validation_2 = modelo_xgb_2.predict(f_validation)

resultados_xgb_2 = evaluar_metricas_modelo(modelo_xgb_2, f_validation, prediccion_xgb_validation_2, t_validation_num, "Modelo 2 - XGBoost",'Segunda iteración')

parametros_xgb_3 = {
    'learning_rate': [0.01], #lo bajo -> mas lento menos overf
    'max_depth': [2,3], #bajo
    'subsample': [0.6, 0.7, 0.8],
    'colsample_bytree': [0.5,0.6,0.7], #bajo
    'n_estimators': [500,700], #lo subo
    'gamma': [0.5, 1.0], #penaliza splits
    'alpha': [0.1, 0.2],
    'lambda': [5.0, 10.0], #subo -> aumenta penalizacion
    'objective': ['binary:logistic']
}

xgb_model_3 = xgb.XGBClassifier(
    objective='binary:logistic',
    n_estimators=100,
    learning_rate=0.1,
    max_depth=3,
    random_state=24
)

random_search_xgb_3 = RandomizedSearchCV(
    estimator=xgb_model_3,
    param_distributions=parametros_xgb_3,
    n_iter=100,
    scoring='f1',
    cv=3,
    random_state=24,
    n_jobs=-1
)

random_search_xgb_3.fit(f_train, t_train_num)

print("Mejores hiperparámetros:", random_search_xgb_3.best_params_)
print("F1 promedio en CV:", random_search_xgb_3.best_score_.round(4))

modelo_xgb_3 = random_search_xgb_3.best_estimator_

prediccion_xgb_validation_3 = modelo_xgb_3.predict(f_validation)

resultados_xgb_3 = evaluar_metricas_modelo(modelo_xgb_3, f_validation, prediccion_xgb_validation_3, t_validation_num, "Modelo 2 - XGBoost",'Tercera iteración')

"""Me quedo con el ```modelo_xgb_3``` que es el que resulto tener mayor ```score```."""

modelo_xgb = modelo_xgb_3
prediccion_xgb_validation = prediccion_xgb_validation_3

"""# Comparación final sobre set validación

En esta sección se compararan bien las metricas de cada uno de los modelos selecciónados sobre el set de validación para tener una idea general de los mismos.

La metrica principal es F1-score sobre la clase Introvert, accuracy y ROC-AUC se muestran unicamente como referencia.
"""

comparacion = pd.DataFrame({
    'Baseline (Reg. Logística)': {
        'Accuracy': accuracy_score(t_validation_num, prediccion_baseline_validation),
        'F1-score (Introvert)': f1_score(t_validation_num, prediccion_baseline_validation),
        'ROC-AUC': roc_auc_score(t_validation_num, modelo_baseline.predict_proba(f_validation)[:, 1])
    },
    'Modelo 1 (Random Forest)': {
        'Accuracy': accuracy_score(t_validation_num, prediccion_rf_validation),
        'F1-score (Introvert)': f1_score(t_validation_num, prediccion_rf_validation),
        'ROC-AUC': roc_auc_score(t_validation_num, modelo_rf.predict_proba(f_validation)[:, 1])
    },
    'Modelo 2 (XGBoost)': {
        'Accuracy': accuracy_score(t_validation_num, prediccion_xgb_validation),
        'F1-score (Introvert)': f1_score(t_validation_num, prediccion_xgb_validation),
        'ROC-AUC': roc_auc_score(t_validation_num, modelo_xgb.predict_proba(f_validation)[:, 1])
    }
}).T.round(4)

comparacion

"""El Baseline (Regresión Logistica) es el que **mejor F1 obtuvo en validación**.
Igualmente, tanto RF como XGBoost obtuvieron un mayor **ROC-AUC**.

# Curva ROC y selección de punto de corte

La **curva ROC** muestra el tradeOff entre dos metricas para **todos los puntos de corte**.
- Eje Y -> TRP (Tasa de verdaderos positivos): de todos los introvertidos reales, la proporcion que detectó el modelo correctamente(Recall).
- Eje X -> FPR (Tasa de falsos positivos): de todos los Extrovertidos reales, la proporció que el modelo clasifico de manera incorrecta como introvertido.

Cada punto de la curva corresponde a un punto de corte de distinto.

Un clasificador perfecto es el que llega a la **esquina superior izquierda**(TPR=1 y FPR=0).

Un clasificador aleatorio segue la diagonal, basicamente seria clasificar al azar.

El **AUC** que es el area bajo de la curva ROC lo que hace es resumir en un solo numero la performance del modelo a lo largo de todos los puntos de corte. Un AUC de 1 es perfecto y un AUC de 0.5 es clasificar al azar.


El punto óptimo de corte se va a determinar sobre el **set de validación** y luego se aplicara al set de test. Si lo hicieramos sobre el set de test, se estaria usando información de set de testeo para tomar una decisión, lo cual haria que se tenga *data leakage* (que es filtrar información).

Para seleccionar el **punto de corte óptimo** se buscara el punto que maximice la diferencia *TPR-FPR*, es decir, el punto de la curva que este mas alejado de la diagonal. Este criterio lo que hace es buscar el mejor balance entre detectar introvertidos correctamente y no clasificar de manera incorrecta a los extrovertidos.
"""

#calculo las probabilidades sobre el set de validacion
proba_baseline_val = modelo_baseline.predict_proba(f_validation)[:, 1]
proba_rf_val= modelo_rf.predict_proba(f_validation)[:, 1]
proba_xgb_val = modelo_xgb.predict_proba(f_validation)[:, 1]

#curvas ROC
#thresholds son los puntos de corte de cada curva
fpr_base,tpr_base, thr_base = roc_curve(t_validation_num, proba_baseline_val)
fpr_rf,tpr_rf, thr_rf = roc_curve(t_validation_num, proba_rf_val)
fpr_xgb,tpr_xgb,thr_xgb  =roc_curve(t_validation_num, proba_xgb_val)

#area bajo la curva roc en cada modelo
auc_base = roc_auc_score(t_validation_num, proba_baseline_val)
auc_rf = roc_auc_score(t_validation_num, proba_rf_val)
auc_xgb = roc_auc_score(t_validation_num, proba_xgb_val)

#el punto de corte opt es el q maximiza tpf-fpr => el punto mas alejado de la diagonal
indice_opt_base = (tpr_base - fpr_base).argmax()
indice_opt_rf = (tpr_rf -fpr_rf).argmax()
indice_opt_xgb = (tpr_xgb - fpr_xgb).argmax()

corte_opt_base = thr_base[indice_opt_base]
corte_opt_rf = thr_rf[indice_opt_rf]
corte_opt_xgb = thr_xgb[indice_opt_xgb]

print(f"Corte óptimo Baseline: {corte_opt_base:.3f}  => TPR={tpr_base[indice_opt_base]:.3f} FPR={fpr_base[indice_opt_base]:.3f}")
print(f"Corte óptimo RF:       {corte_opt_rf:.3f}  => TPR={tpr_rf[indice_opt_rf]:.3f} FPR={fpr_rf[indice_opt_rf]:.3f}")
print(f"Corte óptimo XGBoost:  {corte_opt_xgb:.3f}  => TPR={tpr_xgb[indice_opt_xgb]:.3f} FPR={fpr_xgb[indice_opt_xgb]:.3f}")

"""## Curvas individuales por modelo"""

modelos_roc = [
    {
        'nombre': 'Baseline — Regresión Logística',
        'fpr': fpr_base, 'tpr': tpr_base, 'thr': thr_base,
        'auc': auc_base,
        'idx': indice_opt_base,
        'corte': corte_opt_base,
        'color': 'steelblue'
    },
    {
        'nombre': 'Modelo 1 — Random Forest',
        'fpr': fpr_rf, 'tpr': tpr_rf, 'thr': thr_rf,
        'auc': auc_rf,
        'idx': indice_opt_rf,
        'corte': corte_opt_rf,
        'color': '#239B75'
    },
    {
        'nombre': 'Modelo 2 — XGBoost',
        'fpr': fpr_xgb, 'tpr': tpr_xgb, 'thr': thr_xgb,
        'auc': auc_xgb,
        'idx': indice_opt_xgb,
        'corte': corte_opt_xgb,
        'color': '#D66037'
    },
]

fig, axes = plt.subplots(1, 3, figsize=(20, 6))

for ax, m in zip(axes, modelos_roc):
    idx = m['idx']

    # Curva ROC
    ax.plot(m['fpr'], m['tpr'], color=m['color'], lw=2,
            label=f"AUC = {m['auc']:.4f}")

    # Diagonal (clasificador aleatorio)
    ax.plot([0, 1], [0, 1], color='gray', lw=1.5, linestyle='--', label='Clasificador aleatorio')

    # Punto óptimo
    ax.scatter(m['fpr'][idx], m['tpr'][idx], color=m['color'],
               edgecolors='black', s=120, zorder=5,
               label=f"Umbral óptimo = {m['corte']:.3f}\nTPR={m['tpr'][idx]:.3f}  FPR={m['fpr'][idx]:.3f}")

    ax.plot([m['fpr'][idx], m['fpr'][idx]], [0, m['tpr'][idx]],
            color=m['color'], lw=1, linestyle=':', alpha=0.7)
    ax.plot([0, m['fpr'][idx]], [m['tpr'][idx], m['tpr'][idx]],
            color=m['color'], lw=1, linestyle=':', alpha=0.7)

    ax.set_xlim([0, 1])
    ax.set_ylim([0, 1.02])
    ax.set_xlabel('FPR — Tasa de Falsos Positivos', fontsize=11)
    ax.set_ylabel('TPR — Tasa de Verdaderos Positivos', fontsize=11)
    ax.set_title(m['nombre'], fontsize=12, fontweight='bold')
    ax.legend(loc='lower right', fontsize=10)
    ax.grid(True, alpha=0.3)

plt.suptitle('Curvas ROC por modelo — set de validación', fontsize=14, fontweight='bold', y=1.02)
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 6))

for m in modelos_roc:
    idx = m['idx']
    plt.plot(m['fpr'], m['tpr'], color=m['color'], lw=2,
             label=f"{m['nombre']} (AUC={m['auc']:.4f})")
    plt.scatter(m['fpr'][idx], m['tpr'][idx], color=m['color'],
                edgecolors='black', s=100, zorder=5)

plt.plot([0, 1], [0, 1], color='gray', lw=1.5, linestyle='--', label='Clasificador aleatorio')
plt.xlabel('FPR — Tasa de Falsos Positivos')
plt.ylabel('TPR — Tasa de Verdaderos Positivos')
plt.title('Curvas ROC — comparación de modelos (set de validación)')
plt.legend(loc='lower right')
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

"""## Análisis de resultados

Los puntos marcados sobre las curvas indican el umbral de corte que se selecciono como optimo para cada modelo (es el punto mas alejado de la diagonal).

Como ya se menciono, los puntos de corte se aplicaran en la evaluación del set de testeo.

Respecto al **Baseline - Regresión Logística** el umbral óptimo es muy cercano a 0.5 (que es el default). Es decir, no se necesito un ajuste importante del punto de corte. Ademas, es el que tiene AUC mas bajo entre los tres.

En el modelo de **Random Forest** es en el que mayor AUC se obtuvo, lo que infica que es el que mejor capacidad para discriminar entre las dos clases tiene a lo largo de todos los umbrales posibles. Su corte optimo no se aleja tanto del 0.5 default.

Y en el modelo de **XGBoost**, su punto de corte óptimo es el que mas se aleja del default.

En general, los tres modelos se encuentran muy por encima de la diagonal, lo que significa que todos los modelos aprendieron a discriminar correctamente entre las dos clases de forma efectiva.

La diferencia entre los modelos en cuanto a AUC es muy chiquita. Y el criterio de selección del punto óptimo de corte (maximizar TPF-FPR) prioriza el balance entre detectar introvertidos correctamente y no equivocarse con los extrovertidos clasificandolos incorrecctamente como introvertidos.

## Análisis de CURVA ROC para Regresión Logística
"""

fig, ax = plt.subplots(figsize=(7, 6))

ax.plot(fpr_base, tpr_base, color='steelblue', lw=2,
        label=f'Regresión Logística (AUC = {auc_base:.4f})')

ax.plot([0, 1], [0, 1], color='gray', lw=1.5, linestyle='--',
        label='Clasificador aleatorio (AUC = 0.50)')

ax.scatter(fpr_base[indice_opt_base], tpr_base[indice_opt_base],
           color='steelblue', edgecolors='black', s=150, zorder=5,
           label=(f'Umbral óptimo = {corte_opt_base:.3f}\n'
                  f'TPR = {tpr_base[indice_opt_base]:.3f}   '
                  f'FPR = {fpr_base[indice_opt_base]:.3f}'))

ax.plot([fpr_base[indice_opt_base], fpr_base[indice_opt_base]],
        [0, tpr_base[indice_opt_base]],
        color='steelblue', lw=1, linestyle=':', alpha=0.7)
ax.plot([0, fpr_base[indice_opt_base]],
        [tpr_base[indice_opt_base], tpr_base[indice_opt_base]],
        color='steelblue', lw=1, linestyle=':', alpha=0.7)

ax.annotate(f'  umbral = {corte_opt_base:.3f}',
            xy=(fpr_base[indice_opt_base], tpr_base[indice_opt_base]),
            xytext=(fpr_base[indice_opt_base] + 0.05,
                    tpr_base[indice_opt_base] - 0.06),
            fontsize=10, color='steelblue')

ax.set_xlim([0, 1])
ax.set_ylim([0, 1.02])
ax.set_xlabel('FPR — Tasa de Falsos Positivos', fontsize=12)
ax.set_ylabel('TPR — Tasa de Verdaderos Positivos', fontsize=12)
ax.set_title('Curva ROC — Baseline (Regresión Logística)\nset de validación',
             fontsize=13, fontweight='bold')
ax.legend(loc='lower right', fontsize=10)
ax.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

"""Para la regresión logística, como se mostro anteriormente, el punto de corte óptimo esta muy cerca al que viene por default que es 0.5.

Como se puede observar en la curva ROC, la curva sube rapido a la esquina superior izquierda, lo cual indica un TRP alto y un FPR bajo.

Se uso el TPR-FPR para encontrar el mayor punto porque busca el mejor balance entre detectar a los introvertidos correctamente sin clasificarlos ademas incorrectamente.

Entonces, nuestro modelo nos devuelve una probabilidad del 0 al 1 indicandonos que tan probable es que sea *introvertida* y con el **punto de corte** decimos a partir de *que punto se clasificara como introvertida*.

La curva ROC nos esta mostrando que pasa si cambiamos ese punto de corte desde 0 hasta 1. Osea, si el corte fuera muy bajo (mas cercano a 0) el modelo clasificaria a casi todos como introvertidos, en ese caso detectaria a casi todos los introvertidos reales pero tambien se equivocaria mucho con los extrovertidos reales.
En cambio, si fuese muy alto el modelo casi nunca diria que es introvertido. Es decir, no solo se equivocaria clasificando extrovertidos sino que ademas dejaria de detectar a los introvertidos reales.

Tenemos un **AUC de 0.9638** lo que significa que si tomamos a una persona introvertida y a una extrovertida al azar, el modelo le va a asignar mayor probabilidad de ser introvertida a una persona introvertida en ese porcentaje de casos.

Ademas el corte optimo es 0.575, que es el punto marcado y el que maximiza la diferencia, como ya se menciono, entre los introvertidos detectados correctamente y los extrovertidos mal clasificados. Que el umbral óptimo sea casi el default (0.5) es una buena señal ya que significa que el modelo esta bien calibrado y no necesita un ajuste especial para funcionar bien.

## Actualización de predicciones del set de validación con los nuevos puntos de corte.
"""

prediccion_baseline_validation  = (proba_baseline_val  >= corte_opt_base ).astype(int)
prediccion_rf_validation  = (proba_rf_val  >= corte_opt_rf).astype(int)
prediccion_xgb_validation = (proba_xgb_val >= corte_opt_xgb).astype(int)

# Actualizar tabla comparativa con los umbrales ajustados
comparacion = pd.DataFrame({
    f'Baseline (Reg. Logística)(umbral={corte_opt_base:.2f})': {
        'Accuracy':             accuracy_score(t_validation_num, prediccion_baseline_validation),
        'F1-score (Introvert)': f1_score(t_validation_num, prediccion_baseline_validation),
        'ROC-AUC':              auc_base
    },
    f'RF (umbral={corte_opt_rf:.2f})': {
        'Accuracy':             accuracy_score(t_validation_num, prediccion_rf_validation),
        'F1-score (Introvert)': f1_score(t_validation_num, prediccion_rf_validation),
        'ROC-AUC':              auc_rf
    },
    f'XGBoost (umbral={corte_opt_xgb:.2f})': {
        'Accuracy':             accuracy_score(t_validation_num, prediccion_xgb_validation),
        'F1-score (Introvert)': f1_score(t_validation_num, prediccion_xgb_validation),
        'ROC-AUC':              auc_xgb
    }
}).T.round(4)

comparacion

"""# Feature importance

## Feature importance

Se analiza la importancia de cada feature en los tres modelos. Para **Random Forest** y **XGBoost** se usa ```feature_importances_```, que mide cuanto contribuye cada feature al modelo. Para **Regresion Logística** se usan los *coeficientes del modelo* , como todas las variables estan normalizadas, son compatibles en magnitud entre si. Un coeficiente positivo empuja mas hacia *Introvert*, miesntras uno negativo empuja mas a *Extrovert*.

Para Random Forest y XGBoost se comparan las 10 features mas importantes segun cada modelo. Si ambos coinciden en las mas importantes, es un indicador de que el modelo esta aprendiendo informacion real y no ruido.
"""

fig, axes = plt.subplots(1, 3, figsize=(22, 6))

# Random Forest
importancias_rf = pd.Series(
    modelo_rf.feature_importances_, index=f_train.columns
).sort_values(ascending=False)
sbn.barplot(x=importancias_rf.head(10).values, y=importancias_rf.head(10).index,
            color='#239B75', ax=axes[0])
axes[0].set_title('Top 10 features — Random Forest')
axes[0].set_xlabel('Importancia')

# XGBoost
importancias_xgb = pd.Series(
    modelo_xgb.feature_importances_, index=f_train.columns
).sort_values(ascending=False)
sbn.barplot(x=importancias_xgb.head(10).values, y=importancias_xgb.head(10).index,
            color='#D66037', ax=axes[1])
axes[1].set_title('Top 10 features — XGBoost')
axes[1].set_xlabel('Importancia')

# Regresión Logística
coeficientes = pd.Series(
    modelo_baseline.coef_[0], index=f_train.columns
)
coeficientes_abs = coeficientes.abs().sort_values(ascending=False).head(10)
colores_coef = ['#D66037' if coeficientes[i] > 0 else '#239B75' for i in coeficientes_abs.index]
axes[2].barh(coeficientes_abs.index[::-1], coeficientes_abs.values[::-1], color=colores_coef[::-1])
axes[2].set_title('Top 10 features — Regresión Logística\n(naranja = empuja a Introvert, verde = empuja a Extrovert)')
axes[2].set_xlabel('|Coeficiente| (normalizado)')

plt.tight_layout()
plt.show()

"""Los tres modelos coinciden en que ```Drained_after_socializing``` y ```Stage_fear``` son features importantes, lo cual es consistente con lo visto durante el análisis exploratorio ya que estas mostraban una separacion casi perfecta entre las clases.

Las features creadas en Feature Engineering (```social_score``` y ```social_alone_ratio```) tambien aparecen .

El hecho de que los modelos que son distintos (uno lineal y los otros basados en arboles), coincidan en los features mas relevantes es una buena señal.

## Evaluación de cada feature creada en Feature Engineering

Para medir le impacto de cada nueva feature de forma aislada se entrena **a cada uno de los tres modelos** excluyendo a una feature a la vez, y se compara el **F1-score** sobre el set de validacion.

Se mantendran los hiperparametros de cada modelo.

### Impacto de ```social_score```
"""

cols_sin_social_score = [c for c in f_train.columns if c != 'social_score']

# Baseline
modelo_sin_ss_base = LogisticRegression(C= 0.04, class_weight='balanced', max_iter=1000, random_state=24)
modelo_sin_ss_base.fit(f_train[cols_sin_social_score], t_train_num)
f1_sin_ss_base = f1_score(t_validation_num, modelo_sin_ss_base.predict(f_validation[cols_sin_social_score]))
f1_con_base = f1_score(t_validation_num, modelo_baseline.predict(f_validation))

print("--- Baseline ---")
print(f"F1 sin social_score: {f1_sin_ss_base:.4f}")
print(f"F1 con todas:        {f1_con_base:.4f}")
print(f"Δ =                  {f1_con_base - f1_sin_ss_base:+.4f}")

# Random Forest
modelo_sin_ss_rf = RandomForestClassifier(**modelo_rf.get_params())
modelo_sin_ss_rf.fit(f_train[cols_sin_social_score], t_train_num)
f1_sin_ss_rf = f1_score(t_validation_num, modelo_sin_ss_rf.predict(f_validation[cols_sin_social_score]))
f1_con_rf = f1_score(t_validation_num, modelo_rf.predict(f_validation))

print("\n--- Random Forest ---")
print(f"F1 sin social_score: {f1_sin_ss_rf:.4f}")
print(f"F1 con todas:        {f1_con_rf:.4f}")
print(f"Δ =                  {f1_con_rf - f1_sin_ss_rf:+.4f}")

# XGBoost
modelo_sin_ss_xgb = xgb.XGBClassifier(**modelo_xgb.get_params())
modelo_sin_ss_xgb.fit(f_train[cols_sin_social_score], t_train_num)
f1_sin_ss_xgb = f1_score(t_validation_num, modelo_sin_ss_xgb.predict(f_validation[cols_sin_social_score]))
f1_con_xgb = f1_score(t_validation_num, modelo_xgb.predict(f_validation))

print("\n--- XGBoost ---")
print(f"F1 sin social_score: {f1_sin_ss_xgb:.4f}")
print(f"F1 con todas:        {f1_con_xgb:.4f}")
print(f"Δ =                  {f1_con_xgb - f1_sin_ss_xgb:+.4f}")

"""Su impacto es practicamente nulo en Baseline y RF (Δ = 0.000), lo que indica que la informacion que aporta esta nueva feature ya estaba siendo capturada por las variables numericas que lo componen.

Igualmente, se puede ver que XGBoost si la aprovecha (Δ = +0.0033).

### Impacto de ```social_alone_ratio```
"""

cols_sin_sar = [c for c in f_train.columns if c != 'social_alone_ratio']

# Baseline
modelo_sin_sar_base = LogisticRegression(C= 0.04, class_weight='balanced', max_iter=1000, random_state=24)
modelo_sin_sar_base.fit(f_train[cols_sin_sar], t_train_num)
f1_sin_sar_base = f1_score(t_validation_num, modelo_sin_sar_base.predict(f_validation[cols_sin_sar]))

print("--- Baseline ---")
print(f"F1 sin social_alone_ratio: {f1_sin_sar_base:.4f}")
print(f"F1 con todas:              {f1_con_base:.4f}")
print(f"Δ =                        {f1_con_base - f1_sin_sar_base:+.4f}")

# Random Forest
modelo_sin_sar_rf = RandomForestClassifier(**modelo_rf.get_params())
modelo_sin_sar_rf.fit(f_train[cols_sin_sar], t_train_num)
f1_sin_sar_rf = f1_score(t_validation_num, modelo_sin_sar_rf.predict(f_validation[cols_sin_sar]))

print("\n--- Random Forest ---")
print(f"F1 sin social_alone_ratio: {f1_sin_sar_rf:.4f}")
print(f"F1 con todas:              {f1_con_rf:.4f}")
print(f"Δ =                        {f1_con_rf - f1_sin_sar_rf:+.4f}")

# XGBoost
modelo_sin_sar_xgb = xgb.XGBClassifier(**modelo_xgb.get_params())
modelo_sin_sar_xgb.fit(f_train[cols_sin_sar], t_train_num)
f1_sin_sar_xgb = f1_score(t_validation_num, modelo_sin_sar_xgb.predict(f_validation[cols_sin_sar]))

print("\n--- XGBoost ---")
print(f"F1 sin social_alone_ratio: {f1_sin_sar_xgb:.4f}")
print(f"F1 con todas:              {f1_con_xgb:.4f}")
print(f"Δ =                        {f1_con_xgb - f1_sin_sar_xgb:+.4f}")

"""Es mas consistente que la anterior, tiene Δ positivo para los tres modelos.

Esto confirma que la proporcion entre la vida social y el tiempo solo aporta informacion util que las variables individuales no aportan por si solas.

### Impacto de ```n_missing_answers```
"""

cols_sin_nm = [c for c in f_train.columns if c != 'n_missing_answers']

# Baseline
modelo_sin_nm_base = LogisticRegression(C= 0.04, class_weight='balanced', max_iter=1000, random_state=24)
modelo_sin_nm_base.fit(f_train[cols_sin_nm], t_train_num)
f1_sin_nm_base = f1_score(t_validation_num, modelo_sin_nm_base.predict(f_validation[cols_sin_nm]))

print("--- Baseline ---")
print(f"F1 sin n_missing_answers: {f1_sin_nm_base:.4f}")
print(f"F1 con todas:             {f1_con_base:.4f}")
print(f"Δ =                       {f1_con_base - f1_sin_nm_base:+.4f}")

# Random Forest
modelo_sin_nm_rf = RandomForestClassifier(**modelo_rf.get_params())
modelo_sin_nm_rf.fit(f_train[cols_sin_nm], t_train_num)
f1_sin_nm_rf = f1_score(t_validation_num, modelo_sin_nm_rf.predict(f_validation[cols_sin_nm]))

print("\n--- Random Forest ---")
print(f"F1 sin n_missing_answers: {f1_sin_nm_rf:.4f}")
print(f"F1 con todas:             {f1_con_rf:.4f}")
print(f"Δ =                       {f1_con_rf - f1_sin_nm_rf:+.4f}")

# XGBoost
modelo_sin_nm_xgb = xgb.XGBClassifier(**modelo_xgb.get_params())
modelo_sin_nm_xgb.fit(f_train[cols_sin_nm], t_train_num)
f1_sin_nm_xgb = f1_score(t_validation_num, modelo_sin_nm_xgb.predict(f_validation[cols_sin_nm]))

print("\n--- XGBoost ---")
print(f"F1 sin n_missing_answers: {f1_sin_nm_xgb:.4f}")
print(f"F1 con todas:             {f1_con_xgb:.4f}")
print(f"Δ =                       {f1_con_xgb - f1_sin_nm_xgb:+.4f}")

"""Aporta levemente para XGBoost pero es neutro para Ranfom Forest y Baseline.

### Impacto de ```_era_nula```
"""

cols_era_nula = [c for c in f_train.columns if c.endswith('_era_nula')]
cols_sin_ind = [c for c in f_train.columns if c not in cols_era_nula]

# Baseline
modelo_sin_ind_base = LogisticRegression(C= 0.04, class_weight='balanced', max_iter=1000, random_state=24)
modelo_sin_ind_base.fit(f_train[cols_sin_ind], t_train_num)
f1_sin_ind_base = f1_score(t_validation_num, modelo_sin_ind_base.predict(f_validation[cols_sin_ind]))

print("--- Baseline ---")
print(f"F1 sin indicadores de nulos: {f1_sin_ind_base:.4f}")
print(f"F1 con todas:                {f1_con_base:.4f}")
print(f"Δ =                          {f1_con_base - f1_sin_ind_base:+.4f}")

# Random Forest
modelo_sin_ind_rf = RandomForestClassifier(**modelo_rf.get_params())
modelo_sin_ind_rf.fit(f_train[cols_sin_ind], t_train_num)
f1_sin_ind_rf = f1_score(t_validation_num, modelo_sin_ind_rf.predict(f_validation[cols_sin_ind]))

print("\n--- Random Forest ---")
print(f"F1 sin indicadores de nulos: {f1_sin_ind_rf:.4f}")
print(f"F1 con todas:                {f1_con_rf:.4f}")
print(f"Δ =                          {f1_con_rf - f1_sin_ind_rf:+.4f}")

# XGBoost
modelo_sin_ind_xgb = xgb.XGBClassifier(**modelo_xgb.get_params())
modelo_sin_ind_xgb.fit(f_train[cols_sin_ind], t_train_num)
f1_sin_ind_xgb = f1_score(t_validation_num, modelo_sin_ind_xgb.predict(f_validation[cols_sin_ind]))

print("\n--- XGBoost ---")
print(f"F1 sin indicadores de nulos: {f1_sin_ind_xgb:.4f}")
print(f"F1 con todas:                {f1_con_xgb:.4f}")
print(f"Δ =                          {f1_con_xgb - f1_sin_ind_xgb:+.4f}")

"""Se puede ver que para XGBoost es negativa, es decir, que esta columna lo esta *perjudicando*.

### Resumen impacto individual
"""

resumen_fe = pd.DataFrame({
    'social_score': {
        'Δ F1 Baseline': f1_con_base - f1_sin_ss_base,
        'Δ F1 RF':       f1_con_rf   - f1_sin_ss_rf,
        'Δ F1 XGBoost':  f1_con_xgb  - f1_sin_ss_xgb,
    },
    'social_alone_ratio': {
        'Δ F1 Baseline': f1_con_base - f1_sin_sar_base,
        'Δ F1 RF':       f1_con_rf   - f1_sin_sar_rf,
        'Δ F1 XGBoost':  f1_con_xgb  - f1_sin_sar_xgb,
    },
    'n_missing_answers': {
        'Δ F1 Baseline': f1_con_base - f1_sin_nm_base,
        'Δ F1 RF':       f1_con_rf   - f1_sin_nm_rf,
        'Δ F1 XGBoost':  f1_con_xgb  - f1_sin_nm_xgb,
    },
    'indicadores de nulos': {
        'Δ F1 Baseline': f1_con_base - f1_sin_ind_base,
        'Δ F1 RF':       f1_con_rf   - f1_sin_ind_rf,
        'Δ F1 XGBoost':  f1_con_xgb  - f1_sin_ind_xgb,
    },
}).T.round(4)

resumen_fe.style.background_gradient(cmap='RdYlGn', axis=None)

"""La tabla muestra el ΔF1 de cada feature para cada modelo, un valor positivo indica que la feature **aporta**.

Se puede ver que los ΔF1 son muy chiquitos, lo que significa que las features nuevas no cambian mucho el F1. Esto es esperable porque las features originales, mas que nada ```Stage_fear```y ```Drained_after_socializing``` ya son fuertes predictoras de por si solas.

Que valga 0.0000 no significa que no aporte nada, sino que con la informacion que ya contenia previamente ya estaba captando correctamente.

#### Conclusiones

En la tabla que se mostro previamente, se puede ver el Δ F1 al borrar cada feature. Se puede notar que los deltas son chiquitos, pero como ya se dijo previamente esto es esperable.

En general, el feature engineering tuvo un impacto **positivo en terminos generales**, a scepcion de los indicadores de nulos para XGBoost.

### Impacto global

Para cerrar el análisis, se evalua el impacto de borrar **todas las features generadas durante el feature engineering a la vez**. Esto para ver cuanto aporta el Feature Engineering en conjunto mas alla del aporte individual de cada feature.
"""

cols_fe = ['social_score', 'social_alone_ratio', 'n_missing_answers'] + [c for c in f_train.columns if c.endswith('_era_nula')]
cols_sin_fe = [c for c in f_train.columns if c not in cols_fe]

# Baseline
modelo_sin_fe_base = LogisticRegression(C=0.04, class_weight='balanced', max_iter=1000, random_state=24)
modelo_sin_fe_base.fit(f_train[cols_sin_fe], t_train_num)
f1_sin_fe_base = f1_score(t_validation_num, modelo_sin_fe_base.predict(f_validation[cols_sin_fe]))

print("--- Baseline ---")
print(f"F1 sin Feature Engineering: {f1_sin_fe_base:.4f}")
print(f"F1 con Feature Engineering: {f1_con_base:.4f}")
print(f"Δ =                         {f1_con_base - f1_sin_fe_base:+.4f}")

# Random Forest
modelo_sin_fe_rf = RandomForestClassifier(**modelo_rf.get_params())
modelo_sin_fe_rf.fit(f_train[cols_sin_fe], t_train_num)
f1_sin_fe_rf = f1_score(t_validation_num, modelo_sin_fe_rf.predict(f_validation[cols_sin_fe]))

print("\n--- Random Forest ---")
print(f"F1 sin Feature Engineering: {f1_sin_fe_rf:.4f}")
print(f"F1 con Feature Engineering: {f1_con_rf:.4f}")
print(f"Δ =                         {f1_con_rf - f1_sin_fe_rf:+.4f}")

# XGBoost
modelo_sin_fe_xgb = xgb.XGBClassifier(**modelo_xgb.get_params())
modelo_sin_fe_xgb.fit(f_train[cols_sin_fe], t_train_num)
f1_sin_fe_xgb = f1_score(t_validation_num, modelo_sin_fe_xgb.predict(f_validation[cols_sin_fe]))

print("\n--- XGBoost ---")
print(f"F1 sin Feature Engineering: {f1_sin_fe_xgb:.4f}")
print(f"F1 con Feature Engineering: {f1_con_xgb:.4f}")
print(f"Δ =                         {f1_con_xgb - f1_sin_fe_xgb:+.4f}")

"""Al borrar todas las features creadas, se puede ver que **Baseline** y **Random Forest** se benefician del Feature Engineering en su conjunto, no es una mejora enorme pero mejora al fin. Esto confirma que las features creadas aportan información complementaria.

En cambio para el caso de **XGBoost** sin las features creadas se obtiene un F1 de 0.9395, mientras que con las creadas baja a 0.903. Esto explica en parte porque el XGBoost resulto ser el modelo con menor F1 de los tres.

Como ya se habia dicho antes, el feature Engineering fue **beneficioso para el modelo preseleccionado con el test de validacion que es el de Baseline**.

Podemos pensar tambien que como **Regresión Logistica** es un modelo mas simple, el mismo se beneficia de tener la información *preprocesada y condensada*, mientras que en un modelo mas complejo como **XGBoost** se prefiere quizas trabajan directamente con las variables originales y que el mismo construya sus propias interacciones.

# Evaluación final en Test

Una vez seleccionados los mejores hiperparametros para cada uno de los modelos según el **F1-score** y tambien seleccionado el **punto de corte óptimo** se evaluara una **única vez** cada uno de estos modelos sobre el **set de test**, el cual no fue utilizado en ninguno de los pasos anteriores (ni en el análisis exploratorio de datos, ni en la busqueda de hiperparámetros).

La idea de evaluar contra este **set de test** es simular como funcionaria el modelo en producción con **datos completamente nuevos** para asi poder **estimar la performance real del modelo en producción**.

Para los tres algoritmos se utilizaran los puntos de corte que se determinaron con la curva ROC.

### Baseline
"""

#segun las probabilidades se lo asigna a una clase con el punto de corte establecido
proba_base_test = modelo_baseline.predict_proba(f_test)[:,1]
prediccion_baseline_test = (proba_base_test >= corte_opt_base).astype(int)

resultados_baseline = evaluar_metricas_modelo(modelo_baseline, f_test, prediccion_baseline_test, t_test_num, "Baseline - Regresión Logística sobre set TEST",'')

"""### Random Forest"""

proba_rf_test = modelo_rf.predict_proba(f_test)[:,1]
prediccion_rf_test = (proba_rf_test >= corte_opt_rf).astype(int)

resultados_rf = evaluar_metricas_modelo(modelo_rf, f_test, prediccion_rf_test, t_test_num, "Modelo 1 - Random Forest sobre set TEST",'')

"""### XGBoost"""

proba_xgb_test = modelo_xgb.predict_proba(f_test)[:, 1]
prediccion_xgb_test = (proba_xgb_test >= corte_opt_xgb).astype(int)

resultados_xgb = evaluar_metricas_modelo(modelo_xgb, f_test, prediccion_xgb_test, t_test_num, "Modelo 2 - XGBoost sobre set TEST",'')

"""## Conclusión"""

comparacion_test = pd.DataFrame({
    f'Baseline (Reg. Logística)-(umbral={corte_opt_base:.2f})': {
        'Accuracy':             accuracy_score(t_test_num, prediccion_baseline_test),
        'F1-score (Introvert)': f1_score(t_test_num, prediccion_baseline_test),
        'ROC-AUC':              roc_auc_score(t_test_num, modelo_baseline.predict_proba(f_test)[:, 1])
    },
    f'RF (umbral={corte_opt_rf:.2f})': {
        'Accuracy':             accuracy_score(t_test_num, prediccion_rf_test),
        'F1-score (Introvert)': f1_score(t_test_num, prediccion_rf_test),
        'ROC-AUC':              roc_auc_score(t_test_num, proba_rf_test)
    },
    f'XGBoost (umbral={corte_opt_xgb:.2f})': {
        'Accuracy':             accuracy_score(t_test_num, prediccion_xgb_test),
        'F1-score (Introvert)': f1_score(t_test_num, prediccion_xgb_test),
        'ROC-AUC':              roc_auc_score(t_test_num, proba_xgb_test)
    }
}).T.round(4)

comparacion_test

"""Los tres modelos supereran ampliamente el requisito minimo de **score > 0.8** que en este caso se definio como  **F1 > 0.8**.

El **Baseline** el cual fue implementado con **Regresion Logística** fue el que mejor F1 obtuvo tanto en el set de validación como luego en el set de testeo(confirmandolo).
Esto se puede deber a que tanto ```Stage_fear```y ```Drained_after_socializing``` separan bien las dos clases lo cual hace que la relacion entre estas features y el targer sea *casi lineal* (ya que como se vio en el analisis de datos,las respuesta de estas features tenian una alta coincidencia con el resultado del target). Por lo que **un modelo lineal** captura bien esto.

Igualmente, se puede ver que **Random Forest** y **XGBoost** tienen mayor AUC que el baseline.

Resumiendo, el que resulto ser el **mejor modelo** es el de **Baseline - Regresión Logística con C=0.04** ya que:
- Es el que mejor F1-score sobre la clase Introvert tiene, la cual es la minotaria y la mas dificil de predecir.
- Tambien, aunque no por mucho, pero es la que **mayor accuracy** tiene en general.
- Si bien se le hizo un ajuste en el punto de corte, este es muy cercano al default (0.5), por lo que si se decidiera dejarselo no habria mucha difererncia en cuanto a *performance*.
- Es el de **menor complejidad**, es mas simple y rapido en producción.

Si el criterio que hubiera elegido seria maximizar **ROC-AUC** (que es la capacidad discriminativa a lo largo de todos los puntos de corte posibles) en ese caso el mejor modelo seria **Random Forest**, que es el que mayor **AUC** obtuvo de los tres modelos.
"""

comparacion_test.style.highlight_max(color='Green', axis=0)

"""# Recomendación final

A lo largo de este trabajo se entrenaron y evaluaron tres modelos para predecir la personalidad de una persona (Introvertido/Extrovertido) a partir de variables de comportamiento social.

Los tres modelos planteados superaron el requisito minimo de **F1>0.8**.

## Modelo recomendado : Baseline - Regresión Logística (C=0.04)

A lo largo del trabajo se evaluaron tres modelos: Regresión Logistica (el baseline), Random Forest y XGBoost.
En contra a lo que intuitivamente pense, el modelo mas *simple* (regresión logística) fue el que mejor **F1-score** tuvo tanto en el set de validación como en el set de test.

Esto se debe a que hay dos features que dividen casi perfectamente a las dos clases, es decir, hay una separación de clases casi lineal.
Como se observo durante el análisis exploratorio, las variables ```Stage_fear``` y ```Drained_after_socializing``` tienen una relación muy directa con el target. Quienes respondian ```Yes``` en ambas oportunidades eran en su mayoria introvertidos y viceversa. Esta relación tan directa hace que el modelo no requiera de aprender interacciones muy complejas, anlanzaba justamente con ver cuanto pesaba cada variable para asignarse a una clase.

A lo que voy es que, los modelos de **XGBoost** y **Random Forest** son modelos mas complejos que son capaces de capturar patrones no linenales entre variables, pero para este problema en particular no era necesario.

Entonces, en resumen:

el modelo recomendado para produccion es el **Baseline de Regresión Logistica**, algunas de las razones:
- Es el que mejor F1-score tiene sobre la clase Introvert, tanto en validación como en el set de test.
- Mejor accuracy general. Aunque no es la metrica principal por lo que se explico del desbalance de las clases, el Baseline tambien es el que mayor lo tiene.
- Menor complejidad computacional. La regresion logística es un modelo que entrena *rapido* respecto a los otros, ademas es facil de interpretar.

En este problema en particular, como las variables predictoras tienen una realación casi directa sobre el target, un modelo lineal el cual es mas simple puede superar a modelos mas complejos.

## Conclusión final

El problema de clasificar introvertidos y extrovertidos a partir de las variablse de comportamiento social resulto ser un problema mas orientado a lo lineal, donde las variables ```Stage_fear``` y ```Drained_after_socializin``` separan las clases de forma casi directa. Teniendo en cuenta este contexto, el modelo mas simple fue el mas efectivo.
"""